import { Notice, setIcon } from 'obsidian';
import { activityColor, type PomodoroService } from '../pomodoro-service';

/** Migrated Apex tag manager, backed by the dashboard plugin's own settings. */
export function openPomodoroTagManager(doc: Document, service: PomodoroService, onChange: () => void): void {
	const overlay = doc.body.createDiv({ cls: 'dashboard-pomodoro-stats-overlay mq-pomodoro-apex-theme' });
	const modal = overlay.createDiv({ cls: 'dashboard-pomodoro-stats-modal dashboard-pomodoro-tagmanager' });
	const close = (): void => { doc.removeEventListener('keydown', onKey); overlay.remove(); };
	const onKey = (event: KeyboardEvent): void => { if (event.key === 'Escape') close(); };
	doc.addEventListener('keydown', onKey); overlay.addEventListener('click', (event) => { if (event.target === overlay) close(); });
	const header = modal.createDiv({ cls: 'dashboard-pomodoro-stats-header' }); header.createDiv({ cls: 'dashboard-pomodoro-stats-header-title', text: '活动标签' }); const closeButton = header.createDiv({ cls: 'dashboard-pomodoro-stats-close' }); setIcon(closeButton, 'x'); closeButton.addEventListener('click', close);
	modal.createDiv({ cls: 'dashboard-pomodoro-tagmanager-hint', text: '点击标签可置顶、改名、合并或删除。置顶标签会优先显示在番茄卡片中。' });
	const list = modal.createDiv({ cls: 'dashboard-pomodoro-tagmanager-list' });
	const render = (): void => {
		list.empty(); const names = new Set(service.getTags().map((tag) => tag.name)); for (const name of service.getActivityBreakdown().keys()) if (name && name !== '专注') names.add(name);
		if (!names.size) { list.createDiv({ cls: 'dashboard-pomodoro-donut-empty', text: '暂无活动标签' }); return; }
		for (const name of [...names].sort((a, b) => a.localeCompare(b))) { const tag = service.getTags().find((item) => item.name === name); const row = list.createDiv({ cls: 'dashboard-pomodoro-tagmanager-row' }); const chip = row.createDiv({ cls: 'dashboard-pomodoro-tagmanager-chip' + (tag?.pinned ? ' dashboard-pomodoro-tagmanager-chip--pinned' : '') }); const dot = chip.createDiv({ cls: 'dashboard-pomodoro-donut-legend-dot' }); dot.style.backgroundColor = activityColor(name); chip.createSpan({ cls: 'dashboard-pomodoro-tagmanager-chip-name', text: name }); if (tag?.pinned) setIcon(chip.createSpan({ cls: 'dashboard-pomodoro-tagmanager-chip-pin' }), 'pin'); chip.addEventListener('click', () => row.toggleClass('dashboard-pomodoro-tagmanager-row--open', !row.hasClass('dashboard-pomodoro-tagmanager-row--open')));
			const actions = row.createDiv({ cls: 'dashboard-pomodoro-tagmanager-actions' }); action(actions, tag?.pinned ? 'pin-off' : 'pin', tag?.pinned ? '取消置顶' : '置顶', () => void service.setTagPinned(name, !tag?.pinned).then(refresh)); action(actions, 'pencil', '改名', () => prompt('重命名活动', name, async (value) => { if (!(await service.renameTag(name, value))) throw new Error('名称无效或已存在'); })); action(actions, 'git-merge', '合并', () => prompt('合并到已有标签', '', async (value) => { if (!(await service.mergeTags(name, value))) throw new Error('请选择已有标签'); }, service.getTags().map((item) => item.name).filter((item) => item !== name))); action(actions, 'trash-2', '删除', () => prompt('删除标签并将历史归入“专注”', '', () => service.deleteTag(name), undefined, true)); }
	};
	const refresh = (): void => { render(); onChange(); };
	function action(parent: HTMLElement, icon: string, label: string, handler: () => void): void { const button = parent.createDiv({ cls: 'dashboard-pomodoro-tagmanager-action' + (icon === 'trash-2' ? ' dashboard-pomodoro-tagmanager-action--danger' : '') }); setIcon(button, icon); button.createSpan({ text: label }); button.addEventListener('click', (event) => { event.stopPropagation(); handler(); }); }
	function prompt(label: string, initial: string, submit: (value: string) => Promise<void> | void, options?: string[], danger = false): void { const panel = modal.createDiv({ cls: 'dashboard-pomodoro-tagmanager-prompt' }); panel.createDiv({ cls: 'dashboard-pomodoro-tagmanager-prompt-label', text: label }); const input = options?.length ? panel.createEl('select', { cls: 'dashboard-pomodoro-tagmanager-prompt-select' }) : panel.createEl('input', { cls: 'dashboard-pomodoro-tagmanager-prompt-input', attr: { type: 'text' } }); if (options?.length && input instanceof HTMLSelectElement) for (const value of options) input.add(new Option(value, value)); if (input instanceof HTMLInputElement) input.value = initial; const buttons = panel.createDiv({ cls: 'dashboard-pomodoro-tagmanager-prompt-btns' }); buttons.createEl('button', { cls: 'dashboard-pomodoro-tagmanager-prompt-cancel', text: '取消' }).addEventListener('click', () => panel.remove()); buttons.createEl('button', { cls: 'dashboard-pomodoro-tagmanager-prompt-ok' + (danger ? ' dashboard-pomodoro-tagmanager-prompt-ok--danger' : ''), text: '确认' }).addEventListener('click', () => void Promise.resolve(submit(input.value.trim())).then(() => { panel.remove(); refresh(); }).catch((error) => new Notice(error instanceof Error ? error.message : String(error)))); input.focus(); }
	render();
}
